apiversion: apps/v1
kind: deployment
metadata:
  name: devsecops-app
spec:
  replicas: 1
  selector:
    matchlabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      containers:
      - name: web
        image: ghcr.io/<user>/devsecops-app:latest
        ports:
        - containerport: 3000
      imagepullsecrets:
      - name: ghcr-secret
